$ErrorActionPreference = 'Stop'
$OutputEncoding = [System.Text.UTF8Encoding]::new($false)
[Console]::OutputEncoding = [System.Text.UTF8Encoding]::new($false)
[Console]::InputEncoding = [System.Text.UTF8Encoding]::new($false)

# ── 공유 임계 상수 (단일 진실원) ──────────────────────────────────────────
# CLAUDE.md 줄 제한 — claude-md-size-check.ps1(InstructionsLoaded 가드)과 harness-status
# 스킬이 공유. 두 곳에 독립 하드코딩하면 한쪽만 바뀔 때 drift → 여기로 단일화(AUDIT 매직넘버).
$ClaudeMdLineLimit = 30

function Read-HookInput {
    $raw = [Console]::In.ReadToEnd()
    if ([string]::IsNullOrWhiteSpace($raw)) { return $null }
    try { return $raw | ConvertFrom-Json } catch { return $null }
}

function Write-HookOutput {
    param([Parameter(Mandatory)][hashtable]$Data)
    $json = $Data | ConvertTo-Json -Compress -Depth 12
    [Console]::Out.Write($json)
}

function Get-ProjectRoot {
    if ($env:CLAUDE_PROJECT_DIR) {
        $root = $env:CLAUDE_PROJECT_DIR
        # Safety: env var sometimes carries the .claude/ subdirectory itself (cwd leak from
        # an external invocation). Detect by leaf name and step up — otherwise Get-StateDir
        # creates .claude/.claude/state/ nesting.
        if ((Split-Path $root -Leaf) -eq '.claude') { $root = Split-Path $root -Parent }
        return $root
    }
    # Fallback: this file lives at .claude/hooks/lib/_common.ps1 — three levels up reaches the
    # project root. ($PSScriptRoot inside a function reflects this file's directory, NOT the
    # caller's, because the function was defined here.)
    return (Resolve-Path (Join-Path $PSScriptRoot '..\..\..')).Path
}

function Get-SessionsDir {
    $root = Get-ProjectRoot
    $dir = Join-Path $root 'docs\sessions'
    if (-not (Test-Path $dir)) { New-Item -ItemType Directory -Path $dir -Force | Out-Null }
    return $dir
}

function Get-StateDir {
    $root = Get-ProjectRoot
    $dir = Join-Path $root '.claude\state'
    if (-not (Test-Path $dir)) { New-Item -ItemType Directory -Path $dir -Force | Out-Null }
    return $dir
}

function Get-TodaySessionFile {
    $dir = Get-SessionsDir
    $date = Get-Date -Format 'yyyy-MM-dd'
    $path = Join-Path $dir "$date.md"
    if (-not (Test-Path $path)) {
        $header = @"
# Session log — $date

> Auto-generated by Claude Code harness. Each session appends a block here.
> See [docs/harness.md](../harness.md) for the harness reference.

"@
        try {
            # -NoClobber: if another hook won the race between Test-Path and now, skip
            Set-Content -Path $path -Value $header -Encoding UTF8 -NoNewline -NoClobber -ErrorAction Stop
        } catch {
            # File now exists (race with another hook) — that's fine
        }
    }
    return $path
}

function Get-LatestSessionFile {
    $dir = Get-SessionsDir
    $files = Get-ChildItem -Path $dir -Filter '*.md' -File | Where-Object { $_.Name -match '^\d{4}-\d{2}-\d{2}\.md$' } | Sort-Object Name -Descending
    if ($files.Count -eq 0) { return $null }
    return $files[0].FullName
}

# Walk dated sessions files newest-to-oldest, return the first one containing a "세션 정리" block.
# Used when the very latest file has no wrap-up and we want richer resume context from an earlier session.
# Bound by 30 days (LastWriteTime) — older context is rarely load-bearing and unbounded raw reads
# would slow SessionStart proportionally to total session-log count.
function Get-LatestSessionFileWithWrapup {
    $dir = Get-SessionsDir
    $cutoff = (Get-Date).AddDays(-30)
    $files = Get-ChildItem -Path $dir -Filter '*.md' -File |
        Where-Object { $_.Name -match '^\d{4}-\d{2}-\d{2}\.md$' -and $_.LastWriteTime -gt $cutoff } |
        Sort-Object Name -Descending
    foreach ($f in $files) {
        try {
            $content = Get-Content -Path $f.FullName -Raw -Encoding UTF8 -ErrorAction Stop
            if ($content -match '(?m)^## \[\d{2}:\d{2}\] 세션 정리') { return $f.FullName }
        } catch { continue }
    }
    return $null
}

# Count commits ahead of upstream — returns -1 if no upstream is configured
function Get-UnpushedCommitCount {
    $root = Get-ProjectRoot
    Push-Location $root
    try {
        $upstream = git rev-parse --abbrev-ref --symbolic-full-name '@{u}' 2>$null
        if ([string]::IsNullOrWhiteSpace($upstream) -or $LASTEXITCODE -ne 0) { return -1 }
        $count = git rev-list --count '@{u}..HEAD' 2>$null
        if ([string]::IsNullOrWhiteSpace($count) -or $LASTEXITCODE -ne 0) { return 0 }
        return [int]$count
    } finally {
        Pop-Location
    }
}

function Test-DirtyTree {
    $root = Get-ProjectRoot
    Push-Location $root
    try {
        $status = git status --porcelain 2>$null
        return -not [string]::IsNullOrWhiteSpace($status)
    } finally {
        Pop-Location
    }
}

# git status --porcelain 1회로 dirty/count/클램프를 한 번에 — session-start·pre-compact 가 같은 git 을
# 3회씩(가드+클램프+count) 부르던 것을 1회로(프로세스 생성 비용 절감). 반환: @{ Dirty; Count; Clamped(앞 30줄) }.
function Get-PorcelainStatus {
    $root = Get-ProjectRoot
    Push-Location $root
    try {
        $lines = @(git status --porcelain 2>$null)
    } finally {
        Pop-Location
    }
    return [pscustomobject]@{
        Dirty   = ($lines.Count -gt 0)
        Count   = $lines.Count
        Clamped = (($lines | Select-Object -First 30) -join "`n")
    }
}

function Invoke-WipCommit {
    param([string]$Note = '')
    $root = Get-ProjectRoot
    Push-Location $root
    try {
        $stamp = Get-Date -Format 'yyyy-MM-dd HH:mm'
        $msg = "wip: session $stamp"
        if ($Note) { $msg += " — $Note" }
        git add -A 2>&1 | Out-Null
        git commit -m $msg 2>&1 | Out-Null
        return $LASTEXITCODE -eq 0
    } finally {
        Pop-Location
    }
}

# Push to upstream — used by the "커밋 = 푸시 항상 같이" workflow rule.
# Returns: 'pushed' on success, 'no-upstream' if no tracking branch, 'failed' on push error.
function Invoke-Push {
    $root = Get-ProjectRoot
    Push-Location $root
    try {
        $upstream = git rev-parse --abbrev-ref --symbolic-full-name '@{u}' 2>$null
        if ([string]::IsNullOrWhiteSpace($upstream) -or $LASTEXITCODE -ne 0) { return 'no-upstream' }
        git push 2>&1 | Out-Null
        if ($LASTEXITCODE -eq 0) { return 'pushed' } else { return 'failed' }
    } finally {
        Pop-Location
    }
}

# 변경된 코드/설정 파일 경로 목록 → 동기화가 필요한 docs 목록.
# 구 post-edit-doc-sync.ps1(매 Edit/Write PostToolUse, 콜드스타트 ~245ms/편집)의 매핑을 여기로
# 단일화(P4) — stop-record 가 턴 끝에 dirty 파일을 한 번에 통과시켜 리마인더를 만든다.
# 더 구체적인 패턴(Core/Native/)이 일반형(Core/)보다 앞서야 한다 — 첫 매치 우선.
# 반환: @( @{ Docs=[]; Reason=''; Sample='' } ) — Docs 조합별 1건(dedup).
function Get-DocSyncReminders {
    param([string[]]$Files)
    if (-not $Files -or $Files.Count -eq 0) { return @() }
    $rules = @(
        @{ Pattern = '^Core/Native/'; Docs = @('docs/architecture.md', 'docs/conventions.md'); Reason = 'Core/Native/ 변경 (P/Invoke 시그니처·보안 민감). 새 P/Invoke 면 /security-review 권장.' }
        @{ Pattern = '^App/'; Docs = @('docs/architecture.md', 'docs/implementation-notes.md'); Reason = 'App/ 변경 (애플리케이션 레이어)' }
        @{ Pattern = '^Core/'; Docs = @('docs/architecture.md'); Reason = 'Core/ 변경 (재사용 인프라)' }
        @{ Pattern = '^Program.*\.cs$'; Docs = @('docs/architecture.md', 'docs/implementation-notes.md'); Reason = '엔트리포인트/부트스트랩 변경' }
        @{ Pattern = '^app\.manifest$'; Docs = @('CLAUDE.md', 'docs/conventions.md'); Reason = 'manifest 변경 (P5). UAC/권한 레벨 변경이면 /security-review 권장.' }
        @{ Pattern = 'KoEnVue\.csproj$'; Docs = @('docs/architecture.md', 'docs/release-procedure.md'); Reason = 'csproj 변경 (빌드/버전). NuGet 추가/제거면 /security-review 필수 (P1).' }
        @{ Pattern = '^Directory\.Build\.targets$'; Docs = @('docs/architecture.md', 'docs/conventions.md'); Reason = '빌드 타깃 변경' }
        @{ Pattern = '^NuGet\.config$'; Docs = @('docs/conventions.md'); Reason = 'NuGet 소스 변경 (P1 정신). 외부 피드 추가면 /security-review 필수.' }
        @{ Pattern = '^tests/'; Docs = @('docs/conventions.md'); Reason = '테스트 변경 (CONTRIBUTING)' }
        @{ Pattern = '^\.github/'; Docs = @('CONTRIBUTING.md'); Reason = 'CI 변경' }
        @{ Pattern = '^\.claude/'; Docs = @('docs/harness.md'); Reason = '하네스 설정 변경' }
    )
    $out = @()
    $seen = @{}
    foreach ($f in $Files) {
        if ([string]::IsNullOrWhiteSpace($f)) { continue }
        $norm = $f.Replace('\', '/').TrimStart('/')
        foreach ($rule in $rules) {
            if ($norm -match $rule.Pattern) {
                $key = ($rule.Docs -join ',')
                if (-not $seen.ContainsKey($key)) {
                    $seen[$key] = $true
                    $out += @{ Docs = $rule.Docs; Reason = $rule.Reason; Sample = $norm }
                }
                break
            }
        }
    }
    return $out
}

# Claude Code 기본 auto-memory 위치 (C:) — autoMemoryDirectory(${CLAUDE_PROJECT_DIR} 전개 실패)가
# 무시될 때 실제 읽기/쓰기 위치. slug = 프로젝트 절대경로의 ':' '\' → '-' 치환.
# 드라이브문자 대소문자는 Claude Code 버전에 따라 달랐다 — 2026-07 이전 소문자(e--dev-KoEnVue),
# 이후 원형 유지(E--dev-KoEnVue). 실재하는 변형을 우선 반환하고, 어느 쪽도 없으면 원형 slug 경로를
# 반환한다. **부재 시 $null 을 주지 않는 것이 핵심** — C: 복원 직후엔 디렉토리가 없는 게 정상이고
# 그때가 E:→C: 복구가 가장 필요한 순간이라, $null 로 skip 하면 hook 이 무동작한다(2026-07-22 실측).
function Get-AutoMemoryDir {
    $root = Get-ProjectRoot
    $slug = $root -replace '[:\\]', '-'
    $lower = if ($slug -match '^([A-Za-z])(.*)$') { $matches[1].ToLower() + $matches[2] } else { $slug }
    $base = Join-Path $env:USERPROFILE '.claude\projects'
    foreach ($s in @($slug, $lower)) {
        $dir = Join-Path (Join-Path $base $s) 'memory'
        if (Test-Path $dir) { return $dir }
    }
    return (Join-Path (Join-Path $base $slug) 'memory')
}

# Memory split-brain 동기화 (docs/harness.md §12). E:(.claude/memory, git-tracked, C: 복원 대상 아님)
# = truth, C:(auto-memory) = Claude 가 실제 읽는 작업 사본.
#   (1) C: 의 '더 새로운' 파일만 E: 로 흡수 — 복원된 옛 C: 가 최신 E: 를 못 덮게 mtime(UTC) 비교.
#   (2) E: → C: 미러 — 복원된 C: 를 최신으로 복구, E: 에만 있는 것도 C: 로.
# 삭제는 동기화 안 함(추가/수정만). Copy-Item 은 mtime 보존 → 정상 세션엔 (2)가 무동작.
# C: 디렉토리 부재는 skip 사유가 아니라 **복구 대상** — C: 복원/초기화 직후의 정상 상태이므로
# E: 쪽과 대칭으로 생성한다(2026-07-22: 부재 시 skip 하던 탓에 복원 후 복구가 통째로 불발).
# 반환: @{ absorbed; restored; created }. absorbed>0 이면 E: 변경됨 → 호출부가 commit 판단.
# created=$true 면 C: 가 복원/초기화된 것 → 호출부가 사용자에게 알린다.
function Sync-Memory {
    $cDir = Get-AutoMemoryDir
    $eDir = Join-Path (Get-ProjectRoot) '.claude\memory'
    if (-not (Test-Path $eDir)) { New-Item -ItemType Directory -Path $eDir -Force | Out-Null }
    $created = $false
    if (-not (Test-Path $cDir)) {
        try { New-Item -ItemType Directory -Path $cDir -Force | Out-Null; $created = $true }
        catch { return @{ absorbed = 0; restored = 0; created = $false } }
    }
    $absorbed = 0; $restored = 0
    Get-ChildItem -Path $cDir -Filter '*.md' -File -ErrorAction SilentlyContinue | ForEach-Object {
        try {
            $eFile = Join-Path $eDir $_.Name
            $eItem = Get-Item $eFile -ErrorAction SilentlyContinue
            if (-not $eItem -or $_.LastWriteTimeUtc -gt $eItem.LastWriteTimeUtc) {
                Copy-Item $_.FullName $eFile -Force; $absorbed++
            }
        } catch { }
    }
    Get-ChildItem -Path $eDir -Filter '*.md' -File -ErrorAction SilentlyContinue | ForEach-Object {
        try {
            $cFile = Join-Path $cDir $_.Name
            $cItem = Get-Item $cFile -ErrorAction SilentlyContinue
            if (-not $cItem -or $_.LastWriteTimeUtc -gt $cItem.LastWriteTimeUtc) {
                Copy-Item $_.FullName $cFile -Force; $restored++
            }
        } catch { }
    }
    return @{ absorbed = $absorbed; restored = $restored; created = $created }
}

# Mask common secret patterns before persisting transcript text to git-tracked files
function Hide-Secrets {
    param([string]$Text)
    if ([string]::IsNullOrEmpty($Text)) { return $Text }
    # GitHub personal access / OAuth tokens
    $Text = $Text -replace 'gh[psouru]_[A-Za-z0-9]{20,}', 'gh*_***REDACTED***'
    # Anthropic / OpenAI API keys
    $Text = $Text -replace 'sk-(ant-)?[A-Za-z0-9_\-]{20,}', 'sk-***REDACTED***'
    # Stripe secret keys (sk_test_ / sk_live_) — matched before generic sk- pattern would mistakenly half-redact
    $Text = $Text -replace 'sk_(test|live)_[0-9a-zA-Z]{24,}', 'sk_$1_***REDACTED***'
    # AWS access keys
    $Text = $Text -replace 'AKIA[0-9A-Z]{16}', 'AKIA***REDACTED***'
    # Bearer tokens
    $Text = $Text -replace '(?i)Bearer\s+[A-Za-z0-9_\-+/=.]{20,}', 'Bearer ***REDACTED***'
    # JWT (three base64url segments separated by dots, header typically begins with eyJ)
    $Text = $Text -replace 'eyJ[A-Za-z0-9_\-]{10,}\.eyJ[A-Za-z0-9_\-]{10,}\.[A-Za-z0-9_\-]{10,}', 'eyJ***REDACTED.JWT***'
    # Twilio Account SID
    $Text = $Text -replace 'AC[a-f0-9]{32}', 'AC***REDACTED.TWILIO***'
    # SSH / OpenSSL / PGP private key blocks (multi-line — kept as a single redaction marker)
    $Text = [regex]::Replace($Text, '(?s)-----BEGIN [A-Z ]+PRIVATE KEY-----.*?-----END [A-Z ]+PRIVATE KEY-----', '-----BEGIN PRIVATE KEY-----***REDACTED***-----END PRIVATE KEY-----')
    # GCP service-account JSON fields (private_key_id, private_key)
    $Text = $Text -replace '"private_key_id"\s*:\s*"[a-f0-9]+"', '"private_key_id": "***REDACTED***"'
    $Text = $Text -replace '"private_key"\s*:\s*"-----BEGIN[^"]+"', '"private_key": "***REDACTED***"'
    # Generic API key / password / secret / token assignment
    $Text = $Text -replace '(?i)(api[_-]?key|password|secret|token|access[_-]?key)\s*[:=]\s*["'']?[A-Za-z0-9_+/=.\-]{16,}["'']?', '$1=***REDACTED***'
    # Slack tokens
    $Text = $Text -replace 'xox[abprs]-[A-Za-z0-9\-]{10,}', 'xox*-***REDACTED***'
    return $Text
}

# 워크플로우 meta.phases[].title ↔ 본문 phase()/opts.phase 문자열 집합 정합 검사.
# .claude/workflows/README.md 의 "meta.phases 와 phase() 1:1" 규약을 기계 검증(harness-status 가 호출).
# 휴리스틱(정규식) — meta.phases 블록을 본문에서 제거한 뒤 phase('X') 호출과 opts.phase:'X' 할당을
# 모아 meta 집합과 대조. title 중복·들여쓰기·루프 내 재호출은 Sort-Object -Unique 로 흡수(오탐 방지).
# 반환: 불일치 워크플로우 설명 배열(전부 일치면 @()).
function Test-WorkflowPhaseDrift {
    $wfDir = Join-Path (Get-ProjectRoot) '.claude\workflows'
    if (-not (Test-Path $wfDir)) { return @() }
    $issues = @()
    Get-ChildItem -Path $wfDir -Filter '*.js' -File -ErrorAction SilentlyContinue | ForEach-Object {
        try { $content = Get-Content -Path $_.FullName -Raw -Encoding UTF8 -ErrorAction Stop } catch { return }
        $metaTitles = @()
        $pm = [regex]::Match($content, '(?s)phases\s*:\s*\[(.*?)\]')
        if ($pm.Success) {
            $metaTitles = [regex]::Matches($pm.Groups[1].Value, "title\s*:\s*'([^']*)'") | ForEach-Object { $_.Groups[1].Value }
        }
        $body = $content -replace '(?s)phases\s*:\s*\[.*?\]', ''
        $bodyTitles = @()
        $bodyTitles += [regex]::Matches($body, "\bphase\(\s*'([^']*)'") | ForEach-Object { $_.Groups[1].Value }
        $bodyTitles += [regex]::Matches($body, "\bphase\s*:\s*'([^']*)'") | ForEach-Object { $_.Groups[1].Value }
        $metaSet = @($metaTitles | Sort-Object -Unique)
        $bodySet = @($bodyTitles | Sort-Object -Unique)
        $onlyMeta = @($metaSet | Where-Object { $_ -and $_ -notin $bodySet })
        $onlyBody = @($bodySet | Where-Object { $_ -and $_ -notin $metaSet })
        if ($onlyMeta.Count -or $onlyBody.Count) {
            $desc = $_.BaseName + ':'
            if ($onlyMeta.Count) { $desc += " meta-only[$($onlyMeta -join ',')]" }
            if ($onlyBody.Count) { $desc += " body-only[$($onlyBody -join ',')]" }
            $issues += $desc
        }
    }
    return $issues
}

# 워크플로우 JS 정적 문법검사 — node 로 async 함수 본문 파싱(실행 안 함)해 SyntaxError 만 조기 검출.
# 워크플로우 본문은 런타임이 async 로 실행 → top-level await/return 이 정상이라 `node --check` 는 오탐.
# AsyncFunction 파싱은 await/return 합법 + ESM export 만 제거하면 포맷 일치(check-workflow-syntax.cjs).
# node/스크립트 부재 시 $null(검사 불가 → 침묵 skip). 반환: 문법오류 메시지(정상이면 $null).
function Test-WorkflowSyntax {
    param([Parameter(Mandatory)][string]$JsPath)
    if (-not (Test-Path $JsPath)) { return $null }
    $node = Get-Command node -ErrorAction SilentlyContinue
    if (-not $node) { return $null }
    $checker = Join-Path $PSScriptRoot 'check-workflow-syntax.cjs'
    if (-not (Test-Path $checker)) { return $null }
    # node 의 비-0 exit(문법오류 신호)가 $ErrorActionPreference='Stop' 과 결합해 throw 되지 않도록
    # native 명령 한정으로 억제 — 결과는 $LASTEXITCODE 로 직접 분기한다(PS 7.3+ 는 기본 $true).
    $prevNative = $PSNativeCommandUseErrorActionPreference
    $PSNativeCommandUseErrorActionPreference = $false
    try { $out = & $node.Source $checker $JsPath 2>&1 }
    finally { $PSNativeCommandUseErrorActionPreference = $prevNative }
    if ($LASTEXITCODE -eq 0 -or $LASTEXITCODE -eq 2) { return $null }  # 0=OK, 2=사용오류(문법결함 아님)
    return ($out | Out-String).Trim()
}

# hook-errors.log 일관 포맷 기록 — Invoke-HookSafely catch 경로와 session-end(SessionEnd 는
# additionalContext 못 띄움)의 직접 쓰기가 같은 '[stamp] hook :: msg' 포맷 + rotation 을 공유.
function Write-HookError {
    param([string]$HookName, [string]$Message)
    if ([string]::IsNullOrWhiteSpace($HookName) -or [string]::IsNullOrWhiteSpace($Message)) { return }  # 빈 프로브성 잡음(' :: ') 기록 거부
    try {
        $logPath = Join-Path (Get-StateDir) 'hook-errors.log'
        $stamp = Get-Date -Format 'yyyy-MM-dd HH:mm:ss'
        Add-Content -Path $logPath -Value "[$stamp] $HookName :: $Message" -Encoding UTF8 -ErrorAction SilentlyContinue
        $existing = Get-Content -Path $logPath -Encoding UTF8 -ErrorAction SilentlyContinue
        if ($existing -and $existing.Count -gt 100) {
            Set-Content -Path $logPath -Value ($existing | Select-Object -Last 50) -Encoding UTF8 -ErrorAction SilentlyContinue
        }
    } catch { }
}

# 세션 로그 append 를 named mutex 로 직렬화 — pre-compact/stop-record/session-end 가 거의 동시에
# (auto-compaction 이 turn 종료와 근접) append 할 때 블록 인터리브(깨진 markdown) 방지.
function Add-SessionBlock {
    param([string]$Path, [string]$Content)
    $mutex = New-Object System.Threading.Mutex($false, 'KoEnVue-session-md')
    $acquired = $false
    try {
        try { $acquired = $mutex.WaitOne(2000) } catch [System.Threading.AbandonedMutexException] { $acquired = $true }
        Add-Content -Path $Path -Value $Content -Encoding UTF8
    } finally {
        if ($acquired) { try { $mutex.ReleaseMutex() } catch { } }
        $mutex.Dispose()
    }
}

# Top-level error guard for hooks — log to state dir, never spill into transcript
function Invoke-HookSafely {
    param(
        [Parameter(Mandatory)][scriptblock]$Body,
        [string]$FallbackContext = '',
        [string]$EventName = ''
    )
    try {
        & $Body
    } catch {
        # scriptblock 이 정의된 파일(=호출 hook)을 Ast 로 얻어 'session-start.ps1' 처럼 표기.
        $hookName = try { if ($Body.Ast.Extent.File) { Split-Path -Leaf $Body.Ast.Extent.File } else { 'unknown-hook' } } catch { 'unknown-hook' }
        Write-HookError -HookName $hookName -Message $_.Exception.Message
        # 안전망의 안전망 — context-injecting hook(inject-turn-context 등)이 Write-HookOutput
        # 직전에 죽으면 그 턴의 주입(ultrathink/ultracode/effort)이 통째 증발한다. FallbackContext 가
        # 주어지면 최소 한 줄이라도 내보내 ultracode 항상-ON 의 단일 실패점을 방어.
        if ($FallbackContext -and $EventName) {
            try {
                $fb = @{ hookSpecificOutput = @{ hookEventName = $EventName; additionalContext = $FallbackContext } } | ConvertTo-Json -Compress -Depth 12
                [Console]::Out.Write($fb)
            } catch { }
        }
        exit 0
    }
}
