$ErrorActionPreference = 'Stop'
$OutputEncoding = [System.Text.UTF8Encoding]::new($false)
[Console]::OutputEncoding = [System.Text.UTF8Encoding]::new($false)
[Console]::InputEncoding = [System.Text.UTF8Encoding]::new($false)

function Read-HookInput {
    $raw = [Console]::In.ReadToEnd()
    if ([string]::IsNullOrWhiteSpace($raw)) { return $null }
    try { return $raw | ConvertFrom-Json } catch { return $null }
}

function Write-HookOutput {
    param([Parameter(Mandatory)][hashtable]$Data)
    $json = $Data | ConvertTo-Json -Compress -Depth 12
    [Console]::Out.Write($json)
}

function Get-ProjectRoot {
    if ($env:CLAUDE_PROJECT_DIR) {
        $root = $env:CLAUDE_PROJECT_DIR
        # Safety: env var sometimes carries the .claude/ subdirectory itself (cwd leak from
        # an external invocation). Detect by leaf name and step up — otherwise Get-StateDir
        # creates .claude/.claude/state/ nesting.
        if ((Split-Path $root -Leaf) -eq '.claude') { $root = Split-Path $root -Parent }
        return $root
    }
    # Fallback: this file lives at .claude/hooks/lib/_common.ps1 — three levels up reaches the
    # project root. ($PSScriptRoot inside a function reflects this file's directory, NOT the
    # caller's, because the function was defined here.)
    return (Resolve-Path (Join-Path $PSScriptRoot '..\..\..')).Path
}

function Get-SessionsDir {
    $root = Get-ProjectRoot
    $dir = Join-Path $root 'docs\sessions'
    if (-not (Test-Path $dir)) { New-Item -ItemType Directory -Path $dir -Force | Out-Null }
    return $dir
}

function Get-StateDir {
    $root = Get-ProjectRoot
    $dir = Join-Path $root '.claude\state'
    if (-not (Test-Path $dir)) { New-Item -ItemType Directory -Path $dir -Force | Out-Null }
    return $dir
}

function Get-TodaySessionFile {
    $dir = Get-SessionsDir
    $date = Get-Date -Format 'yyyy-MM-dd'
    $path = Join-Path $dir "$date.md"
    if (-not (Test-Path $path)) {
        $header = @"
# Session log — $date

> Auto-generated by Claude Code harness. Each session appends a block here.
> See [docs/harness.md](../harness.md) for the harness reference.

"@
        try {
            # -NoClobber: if another hook won the race between Test-Path and now, skip
            Set-Content -Path $path -Value $header -Encoding UTF8 -NoNewline -NoClobber -ErrorAction Stop
        } catch {
            # File now exists (race with another hook) — that's fine
        }
    }
    return $path
}

function Get-LatestSessionFile {
    $dir = Get-SessionsDir
    $files = Get-ChildItem -Path $dir -Filter '*.md' -File | Where-Object { $_.Name -match '^\d{4}-\d{2}-\d{2}\.md$' } | Sort-Object Name -Descending
    if ($files.Count -eq 0) { return $null }
    return $files[0].FullName
}

# Walk dated sessions files newest-to-oldest, return the first one containing a "세션 정리" block.
# Used when the very latest file has no wrap-up and we want richer resume context from an earlier session.
# Bound by 30 days (LastWriteTime) — older context is rarely load-bearing and unbounded raw reads
# would slow SessionStart proportionally to total session-log count.
function Get-LatestSessionFileWithWrapup {
    $dir = Get-SessionsDir
    $cutoff = (Get-Date).AddDays(-30)
    $files = Get-ChildItem -Path $dir -Filter '*.md' -File |
        Where-Object { $_.Name -match '^\d{4}-\d{2}-\d{2}\.md$' -and $_.LastWriteTime -gt $cutoff } |
        Sort-Object Name -Descending
    foreach ($f in $files) {
        try {
            $content = Get-Content -Path $f.FullName -Raw -Encoding UTF8 -ErrorAction Stop
            if ($content -match '(?m)^## \[\d{2}:\d{2}\] 세션 정리') { return $f.FullName }
        } catch { continue }
    }
    return $null
}

# Count commits ahead of upstream — returns -1 if no upstream is configured
function Get-UnpushedCommitCount {
    $root = Get-ProjectRoot
    Push-Location $root
    try {
        $upstream = git rev-parse --abbrev-ref --symbolic-full-name '@{u}' 2>$null
        if ([string]::IsNullOrWhiteSpace($upstream) -or $LASTEXITCODE -ne 0) { return -1 }
        $count = git rev-list --count '@{u}..HEAD' 2>$null
        if ([string]::IsNullOrWhiteSpace($count) -or $LASTEXITCODE -ne 0) { return 0 }
        return [int]$count
    } finally {
        Pop-Location
    }
}

function Test-DirtyTree {
    $root = Get-ProjectRoot
    Push-Location $root
    try {
        $status = git status --porcelain 2>$null
        return -not [string]::IsNullOrWhiteSpace($status)
    } finally {
        Pop-Location
    }
}

function Invoke-WipCommit {
    param([string]$Note = '')
    $root = Get-ProjectRoot
    Push-Location $root
    try {
        $stamp = Get-Date -Format 'yyyy-MM-dd HH:mm'
        $msg = "wip: session $stamp"
        if ($Note) { $msg += " — $Note" }
        git add -A 2>&1 | Out-Null
        git commit -m $msg 2>&1 | Out-Null
        return $LASTEXITCODE -eq 0
    } finally {
        Pop-Location
    }
}

# Push to upstream — used by the "커밋 = 푸시 항상 같이" workflow rule.
# Returns: 'pushed' on success, 'no-upstream' if no tracking branch, 'failed' on push error.
function Invoke-Push {
    $root = Get-ProjectRoot
    Push-Location $root
    try {
        $upstream = git rev-parse --abbrev-ref --symbolic-full-name '@{u}' 2>$null
        if ([string]::IsNullOrWhiteSpace($upstream) -or $LASTEXITCODE -ne 0) { return 'no-upstream' }
        git push 2>&1 | Out-Null
        if ($LASTEXITCODE -eq 0) { return 'pushed' } else { return 'failed' }
    } finally {
        Pop-Location
    }
}

# Mask common secret patterns before persisting transcript text to git-tracked files
function Hide-Secrets {
    param([string]$Text)
    if ([string]::IsNullOrEmpty($Text)) { return $Text }
    # GitHub personal access / OAuth tokens
    $Text = $Text -replace 'gh[psouru]_[A-Za-z0-9]{20,}', 'gh*_***REDACTED***'
    # Anthropic / OpenAI API keys
    $Text = $Text -replace 'sk-(ant-)?[A-Za-z0-9_\-]{20,}', 'sk-***REDACTED***'
    # Stripe secret keys (sk_test_ / sk_live_) — matched before generic sk- pattern would mistakenly half-redact
    $Text = $Text -replace 'sk_(test|live)_[0-9a-zA-Z]{24,}', 'sk_$1_***REDACTED***'
    # AWS access keys
    $Text = $Text -replace 'AKIA[0-9A-Z]{16}', 'AKIA***REDACTED***'
    # Bearer tokens
    $Text = $Text -replace '(?i)Bearer\s+[A-Za-z0-9_\-+/=.]{20,}', 'Bearer ***REDACTED***'
    # JWT (three base64url segments separated by dots, header typically begins with eyJ)
    $Text = $Text -replace 'eyJ[A-Za-z0-9_\-]{10,}\.eyJ[A-Za-z0-9_\-]{10,}\.[A-Za-z0-9_\-]{10,}', 'eyJ***REDACTED.JWT***'
    # Twilio Account SID
    $Text = $Text -replace 'AC[a-f0-9]{32}', 'AC***REDACTED.TWILIO***'
    # SSH / OpenSSL / PGP private key blocks (multi-line — kept as a single redaction marker)
    $Text = [regex]::Replace($Text, '(?s)-----BEGIN [A-Z ]+PRIVATE KEY-----.*?-----END [A-Z ]+PRIVATE KEY-----', '-----BEGIN PRIVATE KEY-----***REDACTED***-----END PRIVATE KEY-----')
    # GCP service-account JSON fields (private_key_id, private_key)
    $Text = $Text -replace '"private_key_id"\s*:\s*"[a-f0-9]+"', '"private_key_id": "***REDACTED***"'
    $Text = $Text -replace '"private_key"\s*:\s*"-----BEGIN[^"]+"', '"private_key": "***REDACTED***"'
    # Generic API key / password / secret / token assignment
    $Text = $Text -replace '(?i)(api[_-]?key|password|secret|token|access[_-]?key)\s*[:=]\s*["'']?[A-Za-z0-9_+/=.\-]{16,}["'']?', '$1=***REDACTED***'
    # Slack tokens
    $Text = $Text -replace 'xox[abprs]-[A-Za-z0-9\-]{10,}', 'xox*-***REDACTED***'
    return $Text
}

# Top-level error guard for hooks — log to state dir, never spill into transcript
function Invoke-HookSafely {
    param([Parameter(Mandatory)][scriptblock]$Body)
    try {
        & $Body
    } catch {
        try {
            $logPath = Join-Path (Get-StateDir) 'hook-errors.log'
            $stamp = Get-Date -Format 'yyyy-MM-dd HH:mm:ss'
            # $MyInvocation.ScriptName 은 이 함수가 정의된 _common.ps1 이라 호출 hook 식별 불가 →
            # scriptblock 이 정의된 파일(=호출 hook)을 Ast 로 얻어 'session-start' 처럼 표기.
            $hookName = try { if ($Body.Ast.Extent.File) { Split-Path -Leaf $Body.Ast.Extent.File } else { 'unknown-hook' } } catch { 'unknown-hook' }
            $msg = "[$stamp] $hookName :: $($_.Exception.Message)"
            Add-Content -Path $logPath -Value $msg -Encoding UTF8 -ErrorAction SilentlyContinue

            # Rotation — keep last 50 lines when log exceeds 100
            $existing = Get-Content -Path $logPath -Encoding UTF8 -ErrorAction SilentlyContinue
            if ($existing -and $existing.Count -gt 100) {
                $tail = $existing | Select-Object -Last 50
                Set-Content -Path $logPath -Value $tail -Encoding UTF8 -ErrorAction SilentlyContinue
            }
        } catch { }
        exit 0
    }
}
